// constants/courseConstants.js
export const GET_COURSES_REQUEST = 'GET_COURSES_REQUEST';
export const GET_COURSES_SUCCESS = 'GET_COURSES_SUCCESS';
export const GET_COURSES_FAIL = 'GET_COURSES_FAIL';
  
export const ADD_COURSE_SUCCESS = 'ADD_COURSE_SUCCESS';
export const ADD_COURSE_FAIL = 'ADD_COURSE_FAIL';

export const COURSE_DETAILS_REQUEST = 'COURSE_DETAILS_REQUEST';
export const COURSE_DETAILS_SUCCESS = 'COURSE_DETAILS_SUCCESS';
export const COURSE_DETAILS_FAIL = 'COURSE_DETAILS_FAIL';

export const COURSE_UPDATE_REQUEST = 'COURSE_UPDATE_REQUEST';
export const COURSE_UPDATE_SUCCESS = 'COURSE_UPDATE_SUCCESS';
export const COURSE_UPDATE_FAIL = 'COURSE_UPDATE_FAIL';
