export const GET_ROLE_ID_BY_NAME_REQUEST = "GET_ROLE_ID_BY_NAME_REQUEST";
export const GET_ROLE_ID_BY_NAME_SUCCESS = "GET_ROLE_ID_BY_NAME_SUCCESS";
export const GET_ROLE_ID_BY_NAME_FAIL = "GET_ROLE_ID_BY_NAME_FAIL";

export const CLEAR_ROLE_ERRORS = "CLEAR_ROLE_ERRORS";